### ISSUE TITLE
experimental filesystem

### ISSUE THREAD

**Issue by ahnt** [Hintzelab/MABE#48]
Hi,
#include <experimental/filesystem>
from the development branch doesn't work on xcode/mac 
Cheers Arend

**Comment by cgnitash** [comment]
What version of XCode and clang?

**Comment by ahnt** [comment]
xcode: 9.1 (9B55)
clang:
 Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.0.0

Cheers Arend

**Comment by cgnitash** [comment]
Your compilation should have worked, but the linker will have blown up. On MacOS the libraries are provided by libc++. Fislesystem implementation has been complete since 3.9 http://libcxx.llvm.org/ts1z_status.html
But the linker needs a different option.

Change the line in MBuild.py from '-lstdc++fs' to '-lc++experimental'

**Comment by ahnt** [comment]
I do not use MBuild to compile, I use XCODE 

Cheers Arend

**Comment by cgnitash** [comment]
So however you link all your obj files, at the linking stage add '-lc++experimental'

**Comment by JorySchossau** [comment]
I'll look into adding this to the XCode project generation when I have time.

**Comment by cgnitash** [comment]
population loading no longer requires <experimental/filesystem>. Will add <filesystem> directly when c++17 is available.
development branch should now build on all platforms/IDEs. Shout out if it doesn't.

**Comment by JorySchossau** [comment]
Builds on xcode 9.1 out of the box now! :)
