### ISSUE TITLE
New population loading code doesn't seem to work on Windows 

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#56]
When trying to use the new filesystem to load a population I get the following error: 

 ERROR: MABE requires all files from current directory downwards to be visible.
run "find . -type f > mabe_all_files.txt" before running ./MABE

Running the suggested command results in: 
D:\2017FallResearch\transferMazeWorld\MABE\TEST>find . -type f > mabe_all_files.txt
FIND: Parameter format not correct

**Comment by cgnitash** [comment]
This is simply the command to generate a text file that contains all the path names from the current directory downwards recursively (the file type requirement is optional even) . I have no idea what that command might be in Windows command line. Please go ahead and add it to the error comment when you figure it out.

**Comment by dkirkpatrick** [comment]
Maybe we want to write a python script for this functionality instead of using a system-dependent command?

**Comment by cgnitash** [comment]
Sure, but where would this happen? Can't be in MBuild.py, because I can't rebuild every time my .csv files change. There's no other python script before that, which means we'd have to write another script. Sure, it's a three-liner, but honestly, it seems much easier to include the 2 (at most?) different platform-dependent command line commands that need to be run, directly in the error message.

**Comment by JorySchossau** [comment]
Give it a try now. The code has been updated to be like c++17 filesystem without c++17, and work as Nitash originally had it: automatically.
